name: dart_interval
description: This library provides data structure and operations for intervals in Dart.
version: 0.1.0
homepage: https://github.com/T-Oner/dart_interval

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.16.8